data:
  raw_dir: "shape_net_data/chairs_03001627"     # path to your raw chair npz data
  processed_dir: "shape_net_data/processed"
  splits_dir: "shape_net_data/splits"
  splits:
    train_dir: "shape_net_data/splits/train"
    val_dir: "shape_net_data/splits/val"
    test_dir: "shape_net_data/splits/test"
  split_ratios: [0.7, 0.15, 0.15]

preprocessing:
  voxel_size: 1.0         # or adjust if you want heavier downsampling; 1.0 might be large
  num_points: 2048        # unify each shape to 2048 points
  use_fps: true
  noise_params:
    mean: 0.0
    std: 0.02

training:
  batch_size: 16
  epochs: 50
  learning_rate: 0.001
  betas: [0.9, 0.999]
  scheduler_step_size: 20
  scheduler_gamma: 0.5

model:
  latent_dim: 96
  features_g: [96, 128, 128, 64, 64, 32, 3]
  # IMPORTANT: set 'degrees' so the product = 2048
  # (1 x 2 x 2 x 2 x 2 x 2 x 64 = 2048)
  degrees: [2, 2, 2, 2, 2, 64]
  support: 10
  enc_disc_feat: [3, 64, 128, 256, 512]
  lambda_gp: 10.0
  lambda_nnme: 0.05
  final_num_points: 2048  # just a reference if your code checks it
  save_dir: "models/checkpoints"
  checkpoint_name: "bi_net_checkpoint.pth"